# Generated by Django 4.0.1 on 2022-02-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookshop', '0004_products_discount_products_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tag',
            field=models.CharField(blank=True, default='New', max_length=20, null=True),
        ),
    ]
