# Generated by Django 4.0.1 on 2022-02-20 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebookshop', '0007_customer_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='ebookshop.author'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='ebookshop.category'),
        ),
    ]
