# Generated by Django 4.0.1 on 2022-03-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebookshop', '0009_rename_discount_products_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='quantity',
            new_name='discount',
        ),
    ]
