# Generated by Django 4.0.1 on 2022-03-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookshop', '0010_rename_quantity_products_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
