# Generated by Django 4.0.1 on 2022-03-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookshop', '0011_products_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
