# Generated by Django 4.0.1 on 2022-04-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookshop', '0013_alter_customer_email_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='mobile',
            field=models.CharField(default='8801--------', max_length=50),
        ),
    ]
