# Generated by Django 4.0.1 on 2022-04-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookshop', '0014_shippingaddress_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
    ]
