# Generated by Django 4.0.1 on 2022-04-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookshop', '0015_alter_shippingaddress_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'processing'), ('2', 'package being prepared'), ('3', 'shipping'), ('4', 'shipped'), ('5', 'delivered')], max_length=50, null=True),
        ),
    ]
