# Generated by Django 4.0.1 on 2022-04-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookshop', '0016_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'processing'), ('2', 'package being prepared'), ('3', 'shipping'), ('4', 'shipped'), ('5', 'delivered')], default='processing', max_length=50),
        ),
    ]
