# Generated by Django 4.0.1 on 2022-04-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebookshop', '0021_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
